=== jbittencourt/cooperativa_server/coop_cliente_servidor.dtd
<?xml encoding="UTF-8" ?>

<!-- Created by juliano on 15 de Agosto de 2003, 00:34 -->

<!ELEMENT cooperativa_cliente_servidor ((create_user | identify)+,navigate)>

<!ELEMENT create_user EMPTY> 
<!ELEMENT identify EMPTY>
<!ELEMENT navigate (request_enter_cenario,chat,logout)+>
<!ELEMENT request_enter_cenario EMPTY>
<!ELEMENT chat (enter_cenario| move_to | talk | change_object_state | inventory_add_item | inventory_drop_item)*>
<!ELEMENT enter_cenario EMPTY>
<!ELEMENT move_to EMPTY>
<!ELEMENT talk (#PCDATA)>
<!ELEMENT change_object_state EMPTY>
<!ELEMENT logout EMPTY>
<!ELEMENT inventory_add_item EMPTY>
<!ELEMENT inventory_drop_item EMPTY>


<!--Version of the cliente-->
<!ATTLIST cooperativa_cliente_servidor version CDATA #REQUIRED>

<!ATTLIST create_user username CDATA #REQUIRED>
<!ATTLIST create_user password CDATA #REQUIRED>
<!ATTLIST create_user nomPessoa CDATA #REQUIRED>
<!ATTLIST create_user idAvatar CDATA #REQUIRED>

<!ATTLIST identify username CDATA #REQUIRED>
<!-- Password deve ser um campo criptografado-->
<!ATTLIST identify password CDATA #REQUIRED>

<!ATTLIST request_enter_cenario idcenario CDATA #REQUIRED>
<!-- idpos is identifyer of the cenario window that is being requested. The format of de request is a concat of the x and y
  position of the window in the geometry of the cenario. -->
<!ATTLIST request_enter_cenario celpos CDATA #REQUIRED>
<!ATTLIST request_enter_cenario request_cenario_xml CDATA #REQUIRED>

<!ATTLIST enter_cenario iduser CDATA #REQUIRED>
<!ATTLIST enter_cenario posx CDATA #REQUIRED>
<!ATTLIST enter_cenario posy CDATA #REQUIRED>
<!ATTLIST enter_cenario method CDATA #IMPLIED>

<!ATTLIST move_to posx CDATA #REQUIRED>
<!ATTLIST move_to posy CDATA #REQUIRED>
<!ATTLIST move_to iduser CDATA #REQUIRED>

<!ATTLIST talk iduser CDATA #REQUIRED>

<!ATTLIST change_object_state idobj CDATA #REQUIRED>
<!ATTLIST change_object_state status CDATA #REQUIRED>
<!ATTLIST change_object_state tag CDATA #REQUIRED>
<!ATTLIST change_object_state posx CDATA #REQUIRED>
<!ATTLIST change_object_state posy CDATA #REQUIRED>

<!-- usuario adiciona um item no seu inventario -->
<!ATTLIST inventory_add_item idobj CDATA #REQUIRED>
<!ATTLIST inventory_add_item iduser CDATA #REQUIRED>

<!-- usuario remove um item do seu inventario -->
<!ATTLIST inventory_drop_item idobj CDATA #REQUIRED>
<!ATTLIST inventory_drop_item iduser CDATA #REQUIRED>
<!ATTLIST inventory_drop_item posx CDATA #REQUIRED>
<!ATTLIST inventory_drop_item posy CDATA #REQUIRED>

<!ATTLIST logout iduser CDATA #REQUIRED>

=== jbittencourt/cooperativa_server/teste.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : teste.xml
    Created on : September 16, 2003, 12:04 PM
    Author     : maicon
    Description:
        Purpose of the document follows.
-->



<!DOCTYPE cooperativa_cliente_servidor SYSTEM "http://localhost/coop_cliente_servidor.dtd">
<cooperativa_cliente_servidor version="0.5">
<create_user username="seila" password="seila" nomPessoa="Seila" idAvatar="1" /> 
<identify username="maicon" password="maicon"></identify>
<navigate>
  <request_enter_cenario idcenario="1" celpos="1" request_cenario_xml="0"></request_enter_cenario>
  <chat>
    <enter_cenario iduser="48" posx="10" posy="20"></enter_cenario>
    <talk iduser="48">talk1</talk>
    <talk iduser="48">talk2</talk>
    <move_to iduser="48" posx="10" posy="20"></move_to>
    <change_object_state idobj="1" status="2" tag="45"></change_object_state>  
  </chat>
  <logout iduser="48" />
</navigate>  
</cooperativa_cliente_servidor>

=== jbittencourt/cooperativa_server/cliente_servidor.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : cliente_servidor.xml
    Created on : 29 de Setembro de 2003, 10:17
    Author     : robson
    Description:
        montagem completa de um xml servidor_cliente conforme DTD
        coop_servidor_cliente.dtd.
-->
<!DOCTYPE cooperativa_cliente_servidor SYSTEM "coop_cliente_servidor.dtd">
<cooperativa_cliente_servidor version="1.0">
    <identify username="robson" password="robson"></identify>
    <navigate>
        <request_enter_cenario idcenario="1" celpos="1" request_cenario_xml="" />
        <chat>
            <enter_cenario iduser="1" posx="20" posy="20" method="teleport" />
            <move_to posx="20" posy="20" iduser="1" />
            <talk iduser="1" />
            <change_object_state idobj="12" status="0" tag="0" />
        </chat>
    </navigate>
    <logout iduser="1"/>
</cooperativa_cliente_servidor>
